### ISSUE TITLE
UI menu

### ISSUE THREAD

**Issue by ImIxia** [gabehxd/GameClock#1]
Hi! I can't seem to find a mention of the keybind (or it in itself, tried all the keys) for the config menu, its not mentioned in controls, and I can't find an option for it in settings. I see that you have a picture of it, but not any description of how to get into the menu. 

Thanks for your time! I absolutely love the ability to have the clock in game :D

**Comment by gabehxd** [comment]
I probably should've written this out in the mod description but you can only access the config menu using mod menu
